### ISSUE TITLE
Android build is broken

### ISSUE THREAD

**Issue by nbmrjuhneibkr** [AM2R-Community-Developers/AM2R-Autopatcher-Windows#5]
AM2R-Autopatcher produces an APK file that is identical to AM2RWrapper.apk, and doesn't contain any game data.

**Comment by Lojemiru** [comment]
Of course I'd forget to fix Android while making the changes to get Windows executable patching back online. This should be relatively quick...

**Comment by Lojemiru** [comment]
Resolved. Needed to add a file and lightly edit the packaging routine.
